SESSION_SECRET_KEY = 'CHANGEME'
DATABASE_HOST = '127.0.0.1'
DATABASE_USER = 'sw'
DATABASE_DB = 'sw'
DATABASE_PW = 'CHANGEME'
BASE_URL = 'https://wyborysamorzadpwr.pl' # used in emails
SMTP_FROM_NAME = 'System Wyborczy Samorządu Studenckiego PWr'
SMTP_FROM_ADDR = 'informatyzacja@samorzad.pwr.edu.pl'
SMTP_LOGIN = 'informatyzacja@samorzad.pwr.edu.pl'
SMTP_PW = 'CHANGEME'
SMTP_HOST = 'student.pwr.edu.pl'
SMTP_PORT = 587
