SESSION_SECRET_KEY = 'Kr27hlTzWHBQYXxAAVkZaSpsDVCp4VSAllOXpu605rWw6IpMPaf'
DATABASE_HOST = '127.0.0.1'
DATABASE_USER = 'sw'
DATABASE_DB = 'sw'
DATABASE_PW = 'DATABASE_PASSWORD'
BASE_URL = 'https://systemwyborczy.samorzad.pwr.edu.pl' # used in emails
SMTP_FROM_NAME = 'Studencki System Wyborczy Politechniki Wrocławskiej'
SMTP_FROM_ADDR = 'informatyzacja@samorzad.pwr.edu.pl'
SMTP_HOST = 'localhost'
SMTP_PORT = 6025
